import os
import re
import subprocess
import logging
from pathlib import Path
from typing import Dict, Any, Optional

logger = logging.getLogger(__name__)

def sanitize_filename(name: str) -> str:
    """Sanitizes string for safe filesystem usage."""
    return re.sub(r'[\\/*?:"<>|]', "", name).strip()

def download_audio_from_url(url: str, output_dir: str, progress_callback = None) -> Dict[str, Any]:
    """
    Downloads highest quality audio from YouTube or any media URL using yt-dlp.
    """
    if progress_callback:
        progress_callback(5, "Đang kiểm tra và tải nhạc từ liên kết URL...")

    out_dir = Path(output_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    import yt_dlp

    ydl_opts = {
        'format': 'bestaudio/best',
        'outtmpl': str(out_dir / '%(title)s.%(ext)s'),
        'postprocessors': [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'mp3',
            'preferredquality': '320',
        }],
        'writethumbnail': True,
        'quiet': True,
        'no_warnings': True
    }

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=True)
            title = info.get('title', 'Downloaded_Track')
            duration = info.get('duration', 0)
            thumbnail = info.get('thumbnail', None)

        # Find the generated mp3 file
        mp3_files = list(out_dir.glob("*.mp3"))
        if not mp3_files:
            raise FileNotFoundError("Audio file was not generated by yt-dlp.")

        # Sort by modification time to get the newest
        downloaded_audio = sorted(mp3_files, key=os.path.getmtime)[-1]

        # Rename to clean safe name if needed
        clean_target = out_dir / "source.mp3"
        if downloaded_audio != clean_target:
            if clean_target.exists():
                clean_target.unlink()
            downloaded_audio.rename(clean_target)

        return {
            "title": title,
            "duration": duration,
            "thumbnail": thumbnail,
            "audio_path": str(clean_target)
        }
    except Exception as e:
        logger.error(f"yt-dlp download failed: {e}")
        raise RuntimeError(f"Không thể tải âm thanh từ liên kết: {str(e)}")
