import json
from pathlib import Path
from typing import List, Dict, Any

def format_ass_time(seconds: float) -> str:
    """Formats seconds into ASS timestamp: H:MM:SS.cs (centiseconds)."""
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = int(seconds % 60)
    cs = int(round((seconds - int(seconds)) * 100))
    if cs >= 100:
        cs = 99
    return f"{h}:{m:02d}:{s:02d}.{cs:02d}"

def format_lrc_time(seconds: float) -> str:
    """Formats seconds into LRC timestamp: [mm:ss.xx]."""
    m = int(seconds // 60)
    s = int(seconds % 60)
    cs = int(round((seconds - int(seconds)) * 100))
    if cs >= 100:
        cs = 99
    return f"[{m:02d}:{s:02d}.{cs:02d}]"

def generate_ass_subtitles(
    segments: List[Dict[str, Any]],
    output_ass_path: str,
    font_name: str = "Arial",
    font_size: int = 54,
    primary_color: str = "&H00FFFFFF",     # Inactive text (White in BGR)
    karaoke_color: str = "&H0000E5FF",     # Active sung text (Golden/Yellow/Cyan in BGR)
    outline_color: str = "&H00111111",     # Outline (Dark)
    shadow_color: str = "&H80000000",      # Shadow
    video_width: int = 1920,
    video_height: int = 1080,
    subtitle_pos_y: float = None,          # Legacy or unified percentage
    line1_pos_y: float = None,             # Custom top percentage for Line 1 (e.g. 0.65)
    line2_pos_y: float = None,             # Custom top percentage for Line 2 (e.g. 0.76)
    line1_pos_x: float = None,             # Custom left percentage for Line 1 (e.g. 0.08)
    line2_pos_x: float = None,             # Custom left percentage for Line 2 (e.g. 0.45)
    font_size_line1: int = None,           # Custom font size for Line 1
    font_size_line2: int = None,           # Custom font size for Line 2
    align_line1: str = "left",             # Alignment: "left", "center", "right"
    align_line2: str = "right"             # Alignment: "left", "center", "right"
) -> str:
    r"""
    Generates a professional 2-line alternating Karaoke ASS subtitle file with \kf tags (smooth fill)
    and independent drag & drop 2D (X, Y) placement and font sizes for Line 1 and Line 2.
    """
    # Calculate adaptive margins based on resolution, aspect ratio and custom vertical positions
    is_vertical = video_height > video_width
    scale_factor = video_height / (1920.0 if is_vertical else 1080.0)
    line_gap = int(75 * scale_factor)

    fs1 = int(round((font_size_line1 or font_size) * (1.0 if not is_vertical else scale_factor)))
    fs2 = int(round((font_size_line2 or font_size) * (1.0 if not is_vertical else scale_factor)))

    margin_lr = int(video_width * (0.06 if is_vertical else 0.05))
    outline_val = round(3.5 * scale_factor, 1)
    shadow_val = round(2.0 * scale_factor, 1)

    # 2D X position margin calculation
    x1 = float(line1_pos_x if line1_pos_x is not None else 0.08)
    x2 = float(line2_pos_x if line2_pos_x is not None else 0.42)
    x1 = max(0.02, min(0.85, x1))
    x2 = max(0.02, min(0.85, x2))
    margin_l1 = max(10, int(video_width * x1))
    margin_l2 = max(10, int(video_width * x2))

    if line1_pos_y is not None or line2_pos_y is not None:
        p1 = float(line1_pos_y if line1_pos_y is not None else ((subtitle_pos_y or 0.75) - 0.08))
        p2 = float(line2_pos_y if line2_pos_y is not None else (subtitle_pos_y or 0.75))
        p1 = max(0.08, min(0.92, p1))
        p2 = max(0.08, min(0.92, p2))
        margin_v1 = max(20, int(video_height * (1.0 - p1)))
        margin_v2 = max(20, int(video_height * (1.0 - p2)))
    elif subtitle_pos_y is not None:
        pos_y = max(0.12, min(0.90, float(subtitle_pos_y)))
        margin_v2 = max(30, int(video_height * (1.0 - pos_y)))
        margin_v1 = margin_v2 + line_gap
    else:
        if is_vertical:
            margin_v1 = int(video_height * 0.25)
            margin_v2 = int(video_height * 0.17)
        else:
            margin_v1 = int(140 * scale_factor)
            margin_v2 = int(60 * scale_factor)

    # Determine alignment (1=Left, 2=Center, 3=Right in ASS)
    is_center1 = (align_line1 == "center") or (abs(x1 - 0.50) < 0.06)
    is_center2 = (align_line2 == "center") or (abs(x2 - 0.50) < 0.06)

    align1_val = 2 if is_center1 else 1
    align2_val = 2 if is_center2 else 1

    if is_center1:
        margin_l1 = margin_lr
    if is_center2:
        margin_l2 = margin_lr

    # Colors for Duet roles (ASS uses &HAABBGGRR format)
    color_male = "&H00FEF200"     # Cyan #00F2FE
    color_female = "&H008C75FF"   # Pink #FF758C
    color_duet = "&H0059E2FF"     # Gold #FFE259
    cd_fs = max(24, int(fs1 * 0.55))
    margin_cd = margin_v1 + int(fs1 * 0.9)

    header = f"""[Script Info]
; Script generated by Local AI Karaoke Studio
Title: Karaoke AI
ScriptType: v4.00+
WrapStyle: 2
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601
PlayResX: {video_width}
PlayResY: {video_height}

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: KaraokeLine1_All,{font_name},{fs1},{primary_color},{karaoke_color},{outline_color},{shadow_color},-1,0,0,0,100,100,1,0,1,{outline_val},{shadow_val},{align1_val},{margin_l1},{margin_lr},{margin_v1},1
Style: KaraokeLine2_All,{font_name},{fs2},{primary_color},{karaoke_color},{outline_color},{shadow_color},-1,0,0,0,100,100,1,0,1,{outline_val},{shadow_val},{align2_val},{margin_l2},{margin_lr},{margin_v2},1
Style: KaraokeLine1_Male,{font_name},{fs1},{primary_color},{color_male},{outline_color},{shadow_color},-1,0,0,0,100,100,1,0,1,{outline_val},{shadow_val},{align1_val},{margin_l1},{margin_lr},{margin_v1},1
Style: KaraokeLine2_Male,{font_name},{fs2},{primary_color},{color_male},{outline_color},{shadow_color},-1,0,0,0,100,100,1,0,1,{outline_val},{shadow_val},{align2_val},{margin_l2},{margin_lr},{margin_v2},1
Style: KaraokeLine1_Female,{font_name},{fs1},{primary_color},{color_female},{outline_color},{shadow_color},-1,0,0,0,100,100,1,0,1,{outline_val},{shadow_val},{align1_val},{margin_l1},{margin_lr},{margin_v1},1
Style: KaraokeLine2_Female,{font_name},{fs2},{primary_color},{color_female},{outline_color},{shadow_color},-1,0,0,0,100,100,1,0,1,{outline_val},{shadow_val},{align2_val},{margin_l2},{margin_lr},{margin_v2},1
Style: KaraokeLine1_Duet,{font_name},{fs1},{primary_color},{color_duet},{outline_color},{shadow_color},-1,0,0,0,100,100,1,0,1,{outline_val},{shadow_val},{align1_val},{margin_l1},{margin_lr},{margin_v1},1
Style: KaraokeLine2_Duet,{font_name},{fs2},{primary_color},{color_duet},{outline_color},{shadow_color},-1,0,0,0,100,100,1,0,1,{outline_val},{shadow_val},{align2_val},{margin_l2},{margin_lr},{margin_v2},1
Style: CountdownDotStyle,{font_name},{cd_fs},&H66FFFFFF,{color_duet},{outline_color},{shadow_color},-1,0,0,0,100,100,1,0,1,2,1,2,{margin_lr},{margin_lr},{margin_cd},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
    events = []
    
    for i, seg in enumerate(segments):
        words = seg.get("words", [])
        if not words:
            continue

        start_time = seg["start"]
        end_time = seg["end"]
        role = seg.get("role", "all").capitalize()
        if role not in ["All", "Male", "Female", "Duet"]:
            role = "All"

        # Ensure valid duration
        if end_time <= start_time:
            end_time = start_time + 1.0

        # 2-Line Alternating Timing Schedule:
        style_name = f"KaraokeLine1_{role}" if (i % 2 == 0) else f"KaraokeLine2_{role}"
        cur_fs = fs1 if (i % 2 == 0) else fs2
        is_cur_center = is_center1 if (i % 2 == 0) else is_center2
        cur_margin_l = margin_l1 if (i % 2 == 0) else margin_l2

        # Line i appears on screen as soon as sentence i-2 finishes on the same line position!
        if i == 0:
            display_start = max(0.0, start_time - 3.0)
        elif i == 1:
            display_start = max(0.0, start_time - 2.5)
        else:
            prev_same_line_end = segments[i - 2]["end"]
            display_start = min(start_time - 0.5, prev_same_line_end)

        display_end = end_time + 0.15

        # Lead-in Countdown Dots Event (● ● ● ●) for long intros / interludes (>= 2.5s)
        lead_in_sec = max(0.0, start_time - display_start)
        if lead_in_sec >= 2.2 and i % 2 == 0:
            cd_start = max(display_start, start_time - 2.0)
            cd_end = start_time
            cd_start_ass = format_ass_time(cd_start)
            cd_end_ass = format_ass_time(cd_end)
            cd_text = "{\\k50}● {\\k50}● {\\k50}● {\\k50}●"
            events.append(f"Dialogue: 1,{cd_start_ass},{cd_end_ass},CountdownDotStyle,,0,0,0,,{cd_text}")

        # Smart Auto-Fit Check: Prevent text from clipping at screen edge
        full_line_text = seg.get("text", "".join(w.get("word", "") for w in words))
        est_line_width = len(full_line_text) * cur_fs * 0.62
        max_avail_w = (video_width * 0.90) if is_cur_center else max(300, video_width - cur_margin_l - margin_lr)

        k_text_parts = []
        if est_line_width > max_avail_w and max_avail_w > 200:
            scale = max_avail_w / est_line_width
            scaled_fs = max(28, int(cur_fs * scale))
            k_text_parts.append(f"{{\\fs{scaled_fs}}}")

        # Build karaoke formatted text: {\k<lead_in>} for waiting time, then {\kf<dur>} for words
        if lead_in_sec > 0.05:
            lead_in_cs = int(round(lead_in_sec * 100))
            k_text_parts.append(f"{{\\k{lead_in_cs}}}")

        current_cursor = start_time
        for w_idx, w in enumerate(words):
            w_start = w["start"]
            w_end = w["end"]
            w_text = w["word"]

            lead_gap = max(0.0, w_start - current_cursor)
            if lead_gap >= 0.05:
                gap_cs = int(round(lead_gap * 100))
                if gap_cs > 0:
                    k_text_parts.append(f"{{\\k{gap_cs}}}")

            w_duration = max(0.05, w_end - w_start)
            dur_cs = int(round(w_duration * 100))

            # Use \kf for smooth fluid karaoke fill
            k_text_parts.append(f"{{\\kf{dur_cs}}}{w_text} ")
            current_cursor = w_end

        karaoke_line = "".join(k_text_parts)

        start_ass = format_ass_time(display_start)
        end_ass = format_ass_time(display_end)

        event_line = f"Dialogue: 0,{start_ass},{end_ass},{style_name},,0,0,0,,{karaoke_line}"
        events.append(event_line)

    ass_content = header + "\n".join(events) + "\n"

    out_path = Path(output_ass_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(ass_content, encoding="utf-8")

    return str(out_path)

def generate_lrc(segments: List[Dict[str, Any]], output_lrc_path: str) -> str:
    """Generates standard and word-synced LRC file."""
    lines = []
    lines.append("[ti:AI Karaoke Track]")
    lines.append("[by:Local AI Karaoke Studio]")
    
    for seg in segments:
        words = seg.get("words", [])
        if not words:
            continue
        
        line_start = format_lrc_time(seg["start"])
        word_parts = []
        for w in words:
            w_time = format_lrc_time(w["start"])
            word_parts.append(f"{w_time}{w['word']}")
        
        lines.append(f"{line_start} " + " ".join(word_parts))

    lrc_content = "\n".join(lines) + "\n"
    out_path = Path(output_lrc_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(lrc_content, encoding="utf-8")
    return str(out_path)

def generate_json_lyrics(segments: List[Dict[str, Any]], output_json_path: str) -> str:
    """Saves formatted segments to JSON for real-time web player interaction."""
    out_path = Path(output_json_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(segments, ensure_ascii=False, indent=2), encoding="utf-8")
    return str(out_path)
